server:
   port: 8081
   servlet:
    context-path: /users/

spring:
   data:
      mongodb:
         uri: mongodb+srv://pushpendra:EdL8YuatVzY7j5K@reachoutcluster-kalmu.mongodb.net/pushpendra_enc_demo?retryWrites=true&w=majority

mongodb:
   encrypt:
      silent-decryption-failures: true
      keys:
         - version: 1
           key: 5zkeBHQUgfTZjFvj18eWGeFdu+iygartqdvVba1w32c=